19 update readme
ctu-fgis/2024-b-grass-qgis-colors-convert pull request #20
Opened 2024-06-21 11:43 UTC by jehlijos

Updated reaedme file.

2024-06-23 08:09 UTC, landam requested changes

2024-06-23 08:09 UTC, landam commented on README.md
> +- Add to QGIS: <br>
Add information how to create zip file. From GitHub directly (in this case why to clone reposiotry)? Or by `pb_tool` ?

2024-06-24 07:58 UTC, pesekon2 approved these changes

2024-06-24 08:26 UTC, landam approved these changes

2024-06-24 10:22 UTC, merged