function to convert GRASS tables to QML file
ctu-fgis/2024-b-grass-qgis-colors-convert pull request #6
Opened 2024-04-05 11:06 UTC by jehlijos

color table files for testing added

2024-04-11 09:25 UTC, landam requested changes
The output table could be removed from PR or used for testing (workflows - next step).

2024-04-11 09:25 UTC, landam commented on qgis_color_func.py
> +def conversion(table_path, output_path):
Try to be more specific.  eg:

```suggestion
def convert_color_table_grass_to_qgis(table_path, output_path):
```

2024-04-11 09:25 UTC, landam commented on qgis_color_func.py
> +def conversion(table_path, output_path):
Try to add at least minimalistic docstrings, see https://realpython.com/documenting-python-code/

2024-04-11 09:25 UTC, landam commented on qgis_color_func.py
> +        qml_header = open("qml_form", "r")
Template file should have some file extension for better undestanding, eg.

```suggestion
        qml_header = open("qml_form.template", "r")

```

2024-04-11 09:25 UTC, landam commented on qgis_color_func.py
> +                # refromat percantage from 40% to 0.4
```suggestion
                # refromat percentage from 40% to 0.4
```

Also fix on other lines of code.

2024-04-11 09:25 UTC, landam commented on qgis_color_func.py
> +        # Write the header as first 5 lines from the qml_form file
In general it would be better to use templates like https://docs.python.org/3/library/string.html#string.Template or similar.

2024-04-18 08:29 UTC, landam commented
I tested `elevation` color table on IPR DEM (https://geoportalpraha.cz/data-a-sluzby/97d2c9c11aa9478cb21b469b8a4f820e). After applying generated QML file on DEM I got:

![image](https://github.com/ctu-fgis/2024-b-grass-qgis-colors-convert/assets/5683186/96f01361-f665-41f1-bc43-5d6dff53f782)

which is not correct...

2024-04-18 08:29 UTC, landam requested changes

2024-04-18 08:29 UTC, landam commented on qgis_color_func.py
> +    Output = r"output_tables\qgis\new_table.qml"
```suggestion
    Input = os.path.join("input_tables", "grass", "elevation")
    Output = os.path.join("output_tables", "qgis", "new_table.qml")
```

2024-04-18 08:29 UTC, landam commented on qgis_color_func.py
> +if __name__ == '__main__':
I tested script in QGIS, in this case you need:

```suggestion
if __name__ in ('__main__', '__console__'):
```

2024-04-18 13:47 UTC, landam commented
> I tested `elevation` color table on IPR DEM (https://geoportalpraha.cz/data-a-sluzby/97d2c9c11aa9478cb21b469b8a4f820e). After applying generated QML file on DEM I got:
> 
> ![image](https://private-user-images.githubusercontent.com/5683186/323526401-96f01361-f665-41f1-bc43-5d6dff53f782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDgzMDYsIm5iZiI6MTcxMzQ0ODAwNiwicGF0aCI6Ii81NjgzMTg2LzMyMzUyNjQwMS05NmYwMTM2MS1mNjY1LTQxZjEtYmM0My01ZDZkZmY1M2Y3ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTM0NjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU5MDc5Zjg1MzJhMjU0MzFlMTJlNzdlNjEzODViNjAwMjM2NGI0ZjY4YWE1NWJlZjNkZjkxNzJjZmNmZTNjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1aCTcqDW9T3QRmwhBXVZE7T7uZxiikGwnSw2MtVi7jA)
> 
> which is not correct...

Reported as https://github.com/ctu-fgis/2024-b-grass-qgis-colors-convert/issues/7

2024-04-18 14:00 UTC, landam commented
@jehlijos Please try 
[ndwi.zip](https://github.com/ctu-fgis/2024-b-grass-qgis-colors-convert/files/15025917/ndwi.zip)

range:

```
min=-0.9996841
max=0.6094421
```

![image](https://github.com/ctu-fgis/2024-b-grass-qgis-colors-convert/assets/5683186/33c19415-09ed-4254-98e5-77688e33bffc)

Loaded QML style doesn't work:

![image](https://github.com/ctu-fgis/2024-b-grass-qgis-colors-convert/assets/5683186/8e71c116-0a19-47b5-b765-0fb890aad910)

2024-04-18 14:03 UTC, landam commented
The only color table which should work will be probably only `corine`.

2024-04-18 14:09 UTC, pesekon2 commented
As far as I know, it is not possible to define value ranges in a QML file. Ranges are not handled via `Paletted/Unique values` in QGIS but via `Singleband pseudocolor` instead. And `Singleband pseudocolor` uses txt files for the styles instead of QMLs. See an example of such a txt file below:

```
# QGIS Generated Color Map Export File
INTERPOLATION:INTERPOLATED
359.80078129999998282,247,251,255,255,359.8008
367.17993961899998112,222,235,247,255,367.1799
374.55909793799997942,198,219,239,255,374.5591
381.93825625699997772,158,202,225,255,381.9383
389.31741457599997602,107,174,214,255,389.3174
396.69657289500003117,66,146,198,255,396.6966
404.07573121400002947,33,113,181,255,404.0757
410.88726196999999729,8,81,156,255,410.8873
416.56353760000001785,8,48,107,255,416.5635
```

2024-04-25 14:59 UTC, landam commented
Tested on reclassified (I used `r.reclass` and reclass table from [1]) Corine:

![image](https://github.com/ctu-fgis/2024-b-grass-qgis-colors-convert/assets/5683186/308e1f0c-f6b9-43a2-a20d-71e1beaadd93)


[1] https://grasswiki.osgeo.org/wiki/CORINE_Land_Cover

2024-04-26 08:57 UTC, merged