2 design qgis plugin
ctu-fgis/2024-b-grass-qgis-colors-convert pull request #8
Opened 2024-05-02 19:10 UTC by jehlijos

Working QGIS layout to apply selected GRASS table with absolute values to QGIS layer.
With checkbox to save QML table to file in designated folder with selected file name.

2024-05-11 19:51 UTC, pesekon2 requested changes
Just a little change request from my side. Otherwise, the design looks fine to me and the basic functionality works.

2024-05-11 19:51 UTC, pesekon2 commented on GRASS_GIS_Color_Table_Import_dockwidget.py
> +from qgis_color_func import convert_color_table_grass_to_qgis
Solves issues with relative imports if you do not have the plugin path in your `PYTHONPATH`.

2024-05-13 22:42 UTC, pesekon2 approved these changes

2024-05-14 09:03 UTC, landam approved these changes
Suggestions for this PR:

- remove generated READMEs (html, txt)
- update README.md
- QGIS show default icon (`pb_tool compile` is needed)

Further work (let's discuss it on the next meeting): 
- select GRASS color table should be probably combobox (let's keep it for next PR) 
- replace `tests` with relevant content (let's keep it for next PR)

2024-05-14 09:36 UTC, merged